FROM python:3.11-slim

ENV PIP_TRUSTED_HOST="pypi.org pypi.python.org files.pythonhosted.org"
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir \
    gtfs-realtime-bindings==2.0.0 \
    confluent-kafka==2.3.0 \
    requests==2.31.0 \
    python-dotenv==1.0.1

COPY src/ src/
COPY config/ config/

CMD ["python", "-m", "src.ingestion.gtfs_producer"]
