apiVersion: 1

datasources:
  - name: MTA-Postgres
    uid: mta-postgres
    type: postgres
    url: postgres:5432
    database: mta
    user: mta
    secureJsonData:
      password: mta
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
