-- 1. Create the database
CREATE DATABASE IF NOT EXISTS MTA;

-- 2. Create the schema where raw events will land
CREATE SCHEMA IF NOT EXISTS MTA.RAW;

-- 3. Create the warehouse (if you don't already have one)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
    WAREHOUSE_SIZE = 'X-SMALL' 
    AUTO_SUSPEND = 60 -- suspends after 60s of inactivity (saves cost) 
    AUTO_RESUME = TRUE 
    INITIALLY_SUSPENDED = TRUE
;

-- 4. Create a dedicated role for the pipeline
CREATE ROLE IF NOT EXISTS MTA_TRANSFORMER;

-- 5. Grant the role what it needs
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MTA_TRANSFORMER;
GRANT USAGE ON DATABASE MTA TO ROLE MTA_TRANSFORMER;
GRANT USAGE ON SCHEMA MTA.RAW TO ROLE MTA_TRANSFORMER;
GRANT CREATE STAGE ON SCHEMA MTA.RAW TO ROLE MTA_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA MTA.RAW TO ROLE MTA_TRANSFORMER;
GRANT DELETE, INSERT, SELECT ON FUTURE TABLES IN SCHEMA MTA.RAW TO ROLE MTA_TRANSFORMER;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA MTA.RAW TO ROLE MTA_TRANSFORMER;

-- future tables created in RAW are also covered
GRANT ALL ON TABLE RAW.TRIP_UPDATES TO ROLE MTA_TRANSFORMER;
GRANT ALL ON TABLE RAW.VEHICLE_POSITIONS TO ROLE MTA_TRANSFORMER;
GRANT ALL ON TABLE RAW.ALERTS TO ROLE MTA_TRANSFORMER;
GRANT READ ON STAGE MTA.RAW.S3_STAGE TO ROLE MTA_TRANSFORMER;

-- 6. Create the S3 stage so COPY INTO knows where to read from
--    Replace placeholders with your secure credentials or IAM Role details
CREATE STAGE IF NOT EXISTS MTA.RAW.S3_STAGE 
    URL = 's3://your-bucket-name/raw' 
    CREDENTIALS = (
        AWS_KEY_ID = 'YOUR_AWS_ACCESS_KEY_ID' 
        AWS_SECRET_KEY = 'YOUR_AWS_SECRET_ACCESS_KEY'
    ) 
    FILE_FORMAT = (TYPE = PARQUET)
;

-- 7. Create the user the pipeline will connect as
CREATE USER IF NOT EXISTS mta_oscar 
    PASSWORD = 'YOUR_SECURE_PASSWORD_HERE' 
    DEFAULT_ROLE = MTA_TRANSFORMER 
    DEFAULT_WAREHOUSE = COMPUTE_WH 
    MUST_CHANGE_PASSWORD = TRUE -- Set to TRUE for better security on first login
;

-- 8. Assign the role to the user
GRANT ROLE MTA_TRANSFORMER TO USER mta_oscar;
GRANT ROLE MTA_TRANSFORMER TO USER SOURU0712;

-- 9. Verify everything looks right
SHOW GRANTS TO ROLE MTA_TRANSFORMER;
SHOW STAGES IN SCHEMA MTA.RAW;
SHOW TABLES IN SCHEMA MTA.RAW;

-- Clean old schema
USE ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON TABLE MTA.RAW.MTA_EVENTS TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS; 
TRUNCATE TABLE MTA_EVENTS;